batch_size:
    value: 8
checkpoint_path:
    value: null
cudnn_deterministic:
    value: false
dataset:
    value:
        episodes: null
        image_transforms:
            enable: false
            max_num_transforms: 3
            random_order: false
            tfs:
                affine:
                    kwargs:
                        degrees:
                            - -5
                            - 5
                        translate:
                            - 0.05
                            - 0.05
                    type: RandomAffine
                    weight: 1
                brightness:
                    kwargs:
                        brightness:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                contrast:
                    kwargs:
                        contrast:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                hue:
                    kwargs:
                        hue:
                            - -0.05
                            - 0.05
                    type: ColorJitter
                    weight: 1
                saturation:
                    kwargs:
                        saturation:
                            - 0.5
                            - 1.5
                    type: ColorJitter
                    weight: 1
                sharpness:
                    kwargs:
                        sharpness:
                            - 0.5
                            - 1.5
                    type: SharpnessJitter
                    weight: 1
        repo_id: Aasdfip/full_skewer
        revision: null
        root: null
        streaming: false
        use_imagenet_stats: true
        video_backend: pyav
env:
    value: null
eval:
    value:
        batch_size: 50
        n_episodes: 50
        use_async_envs: false
eval_freq:
    value: 10000000
job_name:
    value: pi05
log_freq:
    value: 30
num_workers:
    value: 4
optimizer:
    value:
        betas:
            - 0.9
            - 0.95
        eps: 1e-08
        grad_clip_norm: 1
        lr: 2.5e-05
        type: adamw
        weight_decay: 0.000000001
output_dir:
    value: outputs/train/pi05_full_skewer_weight_decay
peft:
    value: null
policy:
    value:
        action_expert_variant: gemma_300m
        action_feature_names: null
        chunk_size: 50
        compile_mode: max-autotune
        compile_model: false
        device: cuda
        dtype: bfloat16
        empty_cameras: 0
        freeze_vision_encoder: true
        gradient_checkpointing: false
        image_resolution:
            - 224
            - 224
        input_features:
            observation.images.base_0_rgb:
                shape:
                    - 3
                    - 224
                    - 224
                type: VISUAL
            observation.images.left_wrist_0_rgb:
                shape:
                    - 3
                    - 224
                    - 224
                type: VISUAL
            observation.images.right_wrist_0_rgb:
                shape:
                    - 3
                    - 224
                    - 224
                type: VISUAL
            observation.state:
                shape:
                    - 32
                type: STATE
        license: null
        max_action_dim: 32
        max_period: 4
        max_state_dim: 32
        min_period: 0.004
        n_action_steps: 50
        n_obs_steps: 1
        normalization_mapping:
            ACTION: QUANTILES
            STATE: QUANTILES
            VISUAL: IDENTITY
        num_inference_steps: 10
        optimizer_betas:
            - 0.9
            - 0.95
        optimizer_eps: 1e-08
        optimizer_grad_clip_norm: 1
        optimizer_lr: 2.5e-05
        optimizer_weight_decay: 0.01
        output_features:
            action:
                shape:
                    - 32
                type: ACTION
        paligemma_variant: gemma_2b
        pretrained_path: lerobot/pi05_base
        private: null
        push_to_hub: true
        relative_exclude_joints:
            - gripper
        repo_id: Aasdfip/goldeen_low_weight_decay
        rtc_config: null
        scheduler_decay_lr: 2.5e-06
        scheduler_decay_steps: 30000
        scheduler_warmup_steps: 1000
        tags: null
        time_sampling_beta_alpha: 1.5
        time_sampling_beta_beta: 1
        time_sampling_offset: 0.001
        time_sampling_scale: 0.999
        tokenizer_max_length: 200
        train_expert_only: false
        type: pi05
        use_amp: false
        use_peft: false
        use_relative_actions: false
rabc_epsilon:
    value: 1e-06
rabc_head_mode:
    value: sparse
rabc_kappa:
    value: 0.01
rabc_progress_path:
    value: null
rename_map:
    value:
        observation.images.left_wrist: observation.images.left_wrist_0_rgb
        observation.images.right_top: observation.images.base_0_rgb
        observation.images.right_wrist: observation.images.right_wrist_0_rgb
resume:
    value: false
save_checkpoint:
    value: true
save_freq:
    value: 20000
scheduler:
    value:
        decay_lr: 2.5e-06
        num_decay_steps: 30000
        num_warmup_steps: 1000
        peak_lr: 2.5e-05
        type: cosine_decay_with_warmup
seed:
    value: 1000
steps:
    value: 50000
tolerance_s:
    value: 0.0001
use_policy_training_preset:
    value: true
use_rabc:
    value: false
wandb:
    value:
        add_tags: true
        disable_artifact: false
        enable: true
        entity: null
        mode: null
        notes: null
        project: lerobot
        run_id: null
